name: Go

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.23.2"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Generate
        run: go generate ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -coverprofile=coverage.txt ./...

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

      - name: actions-goveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.txt

      - name: Go report card
        uses: creekorful/goreportcard-action@v1.0
